### ISSUE TITLE
RAW Images initial load

### ISSUE THREAD

**Issue by mschwanzer** [zeitdice/zeitmachine#54]
- Add "Open RAW" button (triggers folder picker)
- If selected folder contains .zd files, load and render as usual.  
- .zd files will be provided by @mattmacdc

**Comment by mschwanzer** [comment]
Camera Sensor Data Sheet: 
http://www.onsemi.com/pub_link/Collateral/MT9P031-D.PDF

**Comment by simonrepp** [comment]
Initial load seems covered to me: cc1dcce8b57d24d6d7792f81ebda46281a0d50f5
